  ace-target-platform-services-db:
   environment:
     AGENT_ID: ace-target-platform-services-db
     AGENT_DISCOVERY_SERVERURLS: conx-apache-ace-server-allinone:8080
   links:
     - conx-apache-ace-server-allinone
   depends_on:
     - conx-apache-ace-copy-repo
   image: conxadmin/apache-ace-conx-target
  conx-apache-ace-copy-repo:
   environment:
     SOURCE_ORG_APACHE_ACE_SERVER: aceserver.myconxdev.com:9000
     SOURCE_ORG_APACHE_ACE_OBR: aceserver.myconxdev.com:9000
     TARGET_ORG_APACHE_ACE_SERVER: conx-apache-ace-server-allinone:8080
     REPO_EXPORTER_TARGETS: platform-services-cms;platform-services-db
   links:
     - conx-apache-ace-server-allinone
   image: conxadmin/apache-ace-conx-client-copy-repo
  conx-apache-ace-server-allinone:
   ports:
     - "8080:8080"
   environment:
     HTTP_PORT: 8080
     ACE_SERVER: localhost:8080
     ACE_OBR: localhost:8080
   image: conxadmin/conx-apache-ace-server-allinone
